[workspace]
resolver = '2'
members = [
    "memsos",
    "kernel",
    "crates/commons",
    "crates/sync",
    "crates/march-c",
    "crates/fb",
    "crates/boot",
    "crates/modulo-n",
    "crates/arch",
    "crates/bit-fade",
    "crates/ui",
    "crates/scheduler",
]

[workspace.dependencies]
commons.path = "./crates/commons"
sync.path = "./crates/sync"
march-c.path = "./crates/march-c"
fb.path = "./crates/fb"
boot.path = "./crates/boot"
modulo-n.path = "./crates/modulo-n"
bit-fade.path = "./crates/bit-fade"
arch.path = "./crates/arch"
limine = "0.5.0"
x86_64 = { version = "0.15.2", default-features = false, features = [
    "instructions",
    "const_fn",
    "abi_x86_interrupt",
    "asm_const",
] }
ui.path = "./crates/ui"
embedded-graphics = "0.8.1"
scheduler.path = "./crates/scheduler"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
