[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11.8"
heapless = "0.8.0"
noto-sans-mono-bitmap = { version = "0.3.0", features = ["unicode-latin-1-supplement"] }
memsos_core = { path = "../core" }
