[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
noto-sans-mono-bitmap = { version = "0.3.0", features = ["unicode-latin-1-supplement"] }
memsos_core = { path = "../core" }
lang = { path = "../lang" }
limine = "0.3.1"

[profile.release]
opt-level = 0
debug = true
codegen-units = 1
lto = false
panic = 'unwind'
incremental = false
overflow-checks = true

