[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
fb.workspace = true
boot.workspace = true
sync.workspace = true
commons.workspace = true
march-c.workspace = true
modulo-n.workspace = true
lazy_static = { version = "1.5.0", default-features = false, features = ["spin_no_std"] }
limine = "0.5.0"
linked_list_allocator = "0.10.5"
x86_64 = { version = "0.15.2", default-features = false, features = ["instructions", "const_fn", "abi_x86_interrupt", "asm_const"] }
