[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
fb.workspace = true
acpi.workspace = true
boot.workspace = true
sync.workspace = true
commons.workspace = true
march-c.workspace = true
ui.workspace = true
modulo-n.workspace = true
arch.workspace = true
lazy_static = { version = "1.5.0", default-features = false, features = [
    "spin_no_std",
] }
limine = "0.5.0"
bit-fade.workspace = true
timers.workspace = true
x86_64.workspace = true
embedded-graphics.workspace = true
x2apic.workspace = true
allocators.workspace = true
paging.workspace = true
pci.workspace = true
