RUST_TARGET := env("RUST_TARGET", "x86_64-unknown-none")
RUST_PROFILE :=  env("RUST_PROFILE", "dev")
RUST_PROFILE_SUBDIR := if RUST_PROFILE == "dev" { "debug" } else { "release" }

obj_cmd := if RUST_PROFILE == "dev" { "objcopy --only-keep-debug kernel kernel.sym" } else { "" }

build:
  RUSTFLAGS="-C relocation-model=static" cargo build --target {{RUST_TARGET}} --profile {{RUST_PROFILE}}
  cp ../target/{{RUST_TARGET}}/{{RUST_PROFILE_SUBDIR}}/kernel kernel
  {{ obj_cmd }}

clean:
  cargo clean
  rm -rf kernel

default: build
