[package]
name = "memsos"
version = "0.1.0"
edition = "2021"

[build-dependencies]
slint-build = "1.11.0"

[dependencies]
slint = { version = "1.11.0", default-features = false, features = ["compat-1-2", "renderer-software", "libm", "log", "unsafe-single-threaded"] }
uefi = { version = "0.35.0", features = ["alloc"], default-features = false }
arch = { path = "../crates/arch/" }
memtest = { path = "../crates/memtest/" }
