[package]
name = "memsos_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.9.0", default-features = false }
rand_chacha = { version = "0.9.0", default-features = false }
heapless = "0.8.0"
