name: Checkout Rust

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string
      name:
        default: cargo-action
        required: false
        type: string
      command:
        default: check
        required: false
        type: string
      args:
        default: ""
        required: false
        type: string

jobs:
  cargo-action:
    permissions:
      contents: read

    name: ${{ inputs.name }}
    runs-on: ${{ inputs.runs-on }}
    steps:

        - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
          with:
            toolchain: stable
  
        - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
          with:
            command: ${{ inputs.command }}
            args: ${{ inputs.args }}