name: CI/CD

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/**/**.rs"
      - "crates/**/**.rs"
      - "kernel/*.rs"

jobs:
  quality-gate:
    permissions:
      contents: read
    uses: RustLangES/workflows/.github/workflows/quality-gate.yml@main
