name: CI/CD

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  quality-gate:
    permissions:
      contents: read
    uses: RustLangES/workflows/.github/workflows/quality-gate.yml@main
