name: Release Build and Publish

permissions:
  contents: write
  pull-requests: read

on:
  push:
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Name of release (optional)"
        required: false
        default: ""
      create_release:
        description: "Create a GitHub release? (true/false)"
        required: false
        default: "false"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate matrix
        id: generate-matrix
        run: |
          LANG_FILES=$(ls crates/lang/defs/*.json)
          LANGUAGES=$(echo "$LANG_FILES" | sed 's|crates/lang/defs/||g' | sed 's|.UTF-8.json||g')

          ARCHITECTURES=("x86_64" "aarch64" "aarch64-uefi" "riscv64-imac" "riscv64-gc")

          MATRIX=$(jq -n '[]')
          for arch in "${ARCHITECTURES[@]}"; do
            for lang in $LANGUAGES; do
              MATRIX=$(echo "$MATRIX" | jq --arg arch "$arch" --arg lang "$lang" '. += [{"arch": $arch, "lang": $lang}]')
            done
          done

          echo "matrix=$(echo "$MATRIX" | jq -c .)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    env:
      RUST_PROFILE: "release"
      ARCH: "${{ matrix.arch }}"
      LANG: "${{ matrix.lang }}"
      IMAGE_NAME: "memsos_${{ matrix.arch }}-${{ matrix.lang }}-${{ github.event.inputs.release_name || (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}"

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Normalize IMAGE_NAME
        run: |
          IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr -cd '[:alnum:]._-')
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Build with Nix
        run: |
          echo "Building for ${{ matrix.arch }} with language ${{ matrix.lang }}..."
          nix build .#${{ matrix.arch }}-${{ matrix.lang }}

          mkdir -p isos
          cp result/memsos-${{ matrix.arch }}-${{ matrix.lang }}.iso isos/${{ env.IMAGE_NAME }}.iso

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso-${{ matrix.arch }}-${{ matrix.lang }}
          path: isos/${{ env.IMAGE_NAME }}.iso

  create-release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ (github.event.inputs.create_release == 'true' || github.event_name == 'push') && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Download ISOs
        uses: actions/download-artifact@v4
        with:
          path: isos

      - name: Combine ISOs into a single folder
        run: |
          mkdir -p combined_isos
          for iso in isos/iso-*/*.iso; do
            cp "$iso" combined_isos/
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          prerelease: ${{ needs.build.outputs.release_name != '' && contains(needs.build.outputs.release_name, 'a') }}
          tag_name: ${{ needs.build.outputs.release_name }}
          name: ${{ needs.build.outputs.release_name }}
          body: ${{ steps.git-cliff.outputs.content }}
          files: |
            combined_isos/*.iso
            CHANGES.md
