name: test and publish

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      
      - name: release
        run: |
          echo "ToDo: release"